import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FirstPage from "../components/FirstPage";
import SecondPage from "../components/SecondPage";
import ThirdPage from "../components/ThirdPage";
import FourthPage from "../components/FourthPage";
import FifthPage from "../components/FifthPage";
import { Suspense } from 'react';
import LoadingPage from "../components/LoadingPage";
import SixthPage from "../components/SixthPage";
import SeventhPage from "../components/SeventhPage";
import EighthPage from "../components/EighthPage";
import FooterPge from "../components/FooterPge";
import {Animate, useElementOnScreen} from "../hooks/useElementOnScreen";
import {useRef} from 'react'

export default function Home() {
    const firstAnimate=useRef();
    useElementOnScreen(firstAnimate);

  return (
    <div>
      <Head>
        <title>Sense Embroidery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
         <Suspense fallback={<LoadingPage></LoadingPage>}>
             <Animate.FadeUp>
             <div className={styles.container}>
                 <FirstPage></FirstPage>
             </div>
             </Animate.FadeUp>

             <Animate.FadeUp>
             <div  className={styles.container}>
                 <SecondPage></SecondPage>
             </div>
             </Animate.FadeUp>

             <Animate.FadeUp>
             <div className={styles.container +' '+styles.container_third}>
                 <ThirdPage></ThirdPage>
             </div>
              </Animate.FadeUp>
             <Animate.FadeUp>
             <div className={styles.container}>
                 <FourthPage></FourthPage>
             </div>
             </Animate.FadeUp>
             <Animate.FadeUp>
             <div className={styles.container}>
                 <FifthPage></FifthPage>
             </div>
             </Animate.FadeUp>

             <Animate.FadeUp>
             <div className={styles.container}>
                 <SixthPage></SixthPage>
             </div>
             </Animate.FadeUp>

             <Animate.FadeUp>
             <div className={styles.container} style={{paddingBottom:'50px'}}>
                 <SeventhPage></SeventhPage>
             </div>
             </Animate.FadeUp>
             <Animate.FadeUp>
             <div className={styles.container}>
                 <EighthPage></EighthPage>
             </div>
             </Animate.FadeUp>
             <Animate.FadeUp>
             <div className={styles.container}>
                 <FooterPge></FooterPge>
             </div>
             </Animate.FadeUp>
         </Suspense>

      </div>
        <footer>
            <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossOrigin={+true}></script>

            <script
                src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
                crossOrigin={+true}></script>

            <script
                src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
                crossOrigin={+true}></script>
        </footer>
    </div>
  )
}
